DROP TABLE IF EXISTS EMPLOYE;
DROP TABLE IF EXISTS NIVEAU_ACCES;
DROP TABLE IF EXISTS LIGUE;

CREATE TABLE LIGUE (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR(100)
);

CREATE TABLE NIVEAU_ACCES (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    niveau_acces VARCHAR(32)
);

CREATE TABLE EMPLOYE (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR(100),
    prenom VARCHAR(100),
    mail VARCHAR(100),
    mdp VARCHAR(32),
    arrive DATE,
    depart DATE,
    id_ligue INT,
    id_niveau_acces INT,
    FOREIGN KEY (id_ligue) REFERENCES LIGUE(id),
    FOREIGN KEY (id_niveau_acces) REFERENCES NIVEAU_ACCES(id)
);